"""Human-review report for candidate traditional-metadata scopes."""

from __future__ import annotations

from collections import Counter
from pathlib import Path

from vedagraph.metadata.ranges import PARSER_VERSION, parse_metadata_value
from vedagraph.models import CandidateMetadataAssertion, QAIssue, SourceAssertion
from vedagraph.models.enums import (
    MetadataPredicate,
    QASeverity,
    RangeParseStatus,
)

DEFERRED_CHECK_ID = "deferred_metadata_range"


def candidates_from_qa(issues: list[QAIssue]) -> list[CandidateMetadataAssertion]:
    """Parse every deferred-range QA warning into a reviewable candidate."""
    candidates: list[CandidateMetadataAssertion] = []
    for issue in issues:
        if issue.check_id != DEFERRED_CHECK_ID or issue.severity != QASeverity.WARNING:
            continue
        predicate = str(issue.details.get("predicate", ""))
        value = str(issue.details.get("value", ""))
        subject = issue.entity_id or ""
        if predicate not in set(MetadataPredicate) or not subject:
            continue
        candidates.append(
            parse_metadata_value(
                subject_id=subject,
                predicate=MetadataPredicate(predicate),
                value=value,
                source_id=str(issue.details.get("source_id", "VHP")),
                source_locator=f"{subject} {predicate}",
            )
        )
    return sorted(candidates, key=lambda item: (item.subject_id, item.predicate))


def candidates_from_assertions(
    assertions: list[SourceAssertion],
) -> list[CandidateMetadataAssertion]:
    """Parse every traditional-metadata source assertion into a reviewable candidate."""
    predicates = {predicate.value for predicate in MetadataPredicate}
    candidates = [
        parse_metadata_value(
            subject_id=assertion.subject_id,
            predicate=MetadataPredicate(assertion.predicate),
            value=str(assertion.value),
            source_id=assertion.source_id,
            source_locator=assertion.source_locator,
        )
        for assertion in assertions
        if assertion.predicate in predicates
    ]
    return sorted(candidates, key=lambda item: (item.subject_id, item.predicate))


REDACTED = "_(withheld: VHP content is not redistributed)_"


def _segment_rows(candidate: CandidateMetadataAssertion, *, redact: bool) -> list[str]:
    if not candidate.segments:
        return ["| _(none)_ | | | | |"]
    rows = []
    for segment in candidate.segments:
        if segment.mantras:
            scope = ", ".join(str(number) for number in segment.mantras)
        elif segment.start_mantra is None:
            scope = "whole passage"
        elif segment.start_mantra == segment.end_mantra:
            scope = str(segment.start_mantra)
        else:
            scope = f"{segment.start_mantra}-{segment.end_mantra}"
        markers = (
            ("yes" if segment.qualifier_markers else "-")
            if redact
            else (", ".join(segment.qualifier_markers) or "-")
        )
        entity = REDACTED if redact else segment.raw_entity
        rows.append(
            f"| `{segment.scope_type}` | {scope} | {entity} | {markers} "
            f"| {'yes' if segment.needs_review else 'no'} |"
        )
    return rows


def render_review(
    candidates: list[CandidateMetadataAssertion], *, redact_source_text: bool = False
) -> str:
    """Render the review. With ``redact_source_text`` the output is safe to commit.

    VHP is a permission-required source, so its verbatim strings never enter Git. The
    redacted report keeps everything the parser produced - statuses, scope types, mantra
    spans, qualifier presence - and withholds only the source text itself.
    """
    status_counts: Counter[RangeParseStatus] = Counter(
        candidate.parse_status for candidate in candidates
    )
    promotable = [candidate for candidate in candidates if candidate.safe_to_promote]
    lines = [
        "# Traditional-metadata range review",
        "",
        "Generated by `vedagraph metadata review-ranges`. Every row is a *candidate*",
        "reading produced by a deterministic parser: nothing has been promoted to",
        "canonical metadata, and nothing may be promoted until a reader who knows the",
        "source notation confirms that the parser understood it.",
        "",
        *(
            [
                "VHP is a permission-required source, so this committed copy withholds the",
                "verbatim source strings and entity text. Run",
                "`vedagraph metadata review-ranges` to write the full report locally; the",
                "path is printed by the command and is excluded from Git.",
                "",
            ]
            if redact_source_text
            else []
        ),
        f"- Parser version: `{PARSER_VERSION}`",
        f"- Metadata strings parsed: {len(candidates)}",
        f"- Marked safe to promote by the parser: {len(promotable)}",
        "",
        "## Status summary",
        "",
        "| Status | Count | Meaning |",
        "| --- | --- | --- |",
        f"| `PARSED` | {status_counts.get(RangeParseStatus.PARSED, 0)} "
        "| Every segment was read without guessing. |",
        f"| `PARTIALLY_PARSED` | {status_counts.get(RangeParseStatus.PARTIALLY_PARSED, 0)} "
        "| Segments were read, but at least one carries a sub-mantra or alternative "
        "qualifier, or depends on a default entity. |",
        f"| `AMBIGUOUS` | {status_counts.get(RangeParseStatus.AMBIGUOUS, 0)} "
        "| A segment could not be attached to a scope without an interpretive choice. |",
        f"| `UNSUPPORTED` | {status_counts.get(RangeParseStatus.UNSUPPORTED, 0)} "
        "| The string uses a form outside the observed grammar. |",
        f"| `INVALID` | {status_counts.get(RangeParseStatus.INVALID, 0)} "
        "| Nothing could be read at all. |",
        "",
        "## Candidates",
        "",
    ]
    for candidate in candidates:
        lines.extend(
            [
                f"### {candidate.subject_id} - {candidate.predicate}",
                "",
                f"- Source: `{candidate.source_id}` at `{candidate.source_locator}`",
                f"- Parse status: **{candidate.parse_status}**",
                f"- Safe to promote: **{'yes' if candidate.safe_to_promote else 'no'}**",
                f"- Parser note: {candidate.notes or 'none'}",
                "",
                "Original source string:",
                "",
                f"> {REDACTED if redact_source_text else candidate.raw_value}",
                "",
                "| Scope type | Mantras | Raw entity | Qualifier markers | Needs review |",
                "| --- | --- | --- | --- | --- |",
                *_segment_rows(candidate, redact=redact_source_text),
                "",
            ]
        )
        if candidate.unparsed_remainder:
            lines.extend(
                [
                    "Not interpreted:",
                    "",
                    *(
                        [f"- {len(candidate.unparsed_remainder)} segment(s), {REDACTED}"]
                        if redact_source_text
                        else [f"- `{item}`" for item in candidate.unparsed_remainder]
                    ),
                    "",
                ]
            )
    lines.extend(
        [
            "## What a reviewer must decide",
            "",
            "1. Whether each `raw_entity` string is the entity the source intended. Entity",
            "   resolution to a Vedic entity registry is deliberately out of scope here.",
            "2. Whether a leading unscoped entity really applies to every mantra not named",
            "   by a later segment, or only to the mantras before the first exception.",
            "3. How half-verse and pada scopes should be represented canonically. They are",
            "   preserved verbatim rather than widened into whole-mantra claims.",
            "4. Whether an `AMBIGUOUS` or `UNSUPPORTED` string should be encoded by hand.",
            "",
            "No candidate is written into `traditional_metadata.jsonl` by this session.",
            "",
        ]
    )
    return "\n".join(lines)


def write_review(
    candidates: list[CandidateMetadataAssertion],
    path: Path,
    *,
    redact_source_text: bool = False,
) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        render_review(candidates, redact_source_text=redact_source_text),
        encoding="utf-8",
        newline="\n",
    )
    return path
