"""Figure: one entity, four epistemic layers -- the neighbourhood of Indra.

Emits figures/fig_indra_generated.tex (a TikZ fragment), queried live so the figure
cannot drift from the graph.

SELECTION CRITERIA, stated because a curated subgraph is an argument and an
uncurated one is a hairball:

  1. Subject: the :Devata node whose display_label is exactly "Indra"
     (VG:DEVATA:INDRAH). Chosen for connectivity: it is the most frequently
     dedicated deity in the corpus (2,869 HAS_DEVATA edges,
     against 1,988 for Agni; verified in fact_freeze.rankings).
  2. High-cardinality passage predicates (MENTIONS_DEVATA, HAS_DEVATA,
     HAS_DEVATA_DERIVED, ASSERTION_AGENT) are AGGREGATED into one labelled edge per
     (predicate, layer, attribution-precision) triple. Drawing 6,000 individual
     passage edges would communicate nothing.
  3. Low-cardinality typed neighbours are drawn individually and capped: the top 5
     co-occurring deities by lift, the top 5 action predicates, all 5 epithets, all
     3 deity axes, and both concept associations.
  4. Every edge is coloured by its stored knowledge_layer. No edge is drawn whose
     layer is inferred by this script.

    python figures-src/fig_indra.py
"""

from __future__ import annotations

import os
from pathlib import Path

from dotenv import load_dotenv
from neo4j import GraphDatabase

ROOT = Path(__file__).resolve().parents[3]
OUT = Path(__file__).resolve().parents[1] / "figures" / "fig_indra_generated.tex"
KEY = "VG:DEVATA:INDRAH"

STYLE = {
    "L1_SOURCE_EXPLICIT": "l1",
    "L2_DETERMINISTIC_DERIVED": "l2",
    "DETERMINISTIC_DERIVED": "l2",
    "L3_LLM_EXTRACTED": "l3",
    "L4_INTERPRETIVE_CLAIM": "l4",
}


def thou(v: int) -> str:
    """LaTeX thousands separator that cannot be confused with a coordinate comma."""
    return f"{v:,}".replace(",", "{,}")


def tex(s: str) -> str:
    """Escape a display label for LaTeX. Labels carry IAST, which XeTeX sets
    directly, so only the reserved characters need handling."""
    for a, b in [
        ("\\", "\\textbackslash{}"),
        ("&", "\\&"),
        ("%", "\\%"),
        ("$", "\\$"),
        ("#", "\\#"),
        ("_", "\\_"),
        ("{", "\\{"),
        ("}", "\\}"),
        ("~", "\\textasciitilde{}"),
        ("^", "\\textasciicircum{}"),
    ]:
        s = s.replace(a, b)
    return s


def main() -> int:
    load_dotenv(ROOT / ".env")
    drv = GraphDatabase.driver(
        os.environ["NEO4J_URI"],
        auth=(os.environ["NEO4J_USER"], os.environ["NEO4J_PASSWORD"]),
    )

    def q(cy: str) -> list[dict]:
        with drv.session(database=os.environ.get("NEO4J_DATABASE", "neo4j")) as s:
            return s.run(cy, k=KEY).data()

    agg = q(
        "MATCH (p:Passage)-[r:HAS_DEVATA|MENTIONS_DEVATA|HAS_DEVATA_DERIVED]->"
        "(n:Devata {entity_key:$k}) "
        "RETURN type(r) AS t, r.knowledge_layer AS kl, r.attribution_precision AS ap, "
        "count(*) AS n ORDER BY n DESC"
    )
    assertions = q(
        "MATCH (a:SemanticAssertion)-[r:ASSERTION_AGENT]->(n:Devata {entity_key:$k}) "
        "RETURN a.derivation AS der, a.knowledge_layer AS kl, count(*) AS n "
        "ORDER BY n DESC"
    )
    cooc = q(
        "MATCH (n:Devata {entity_key:$k})-[r:CO_OCCURS_WITH]->(m) "
        "RETURN m.display_label AS l, r.lift AS lift, r.knowledge_layer AS kl "
        "ORDER BY coalesce(r.lift,0) DESC LIMIT 5"
    )
    acts = q(
        "MATCH (n:Devata {entity_key:$k})-[r:PERFORMS_ACTION]->(m) "
        "RETURN m.display_label AS l, r.knowledge_layer AS kl "
        "ORDER BY m.display_label LIMIT 5"
    )
    epith = q(
        "MATCH (n:Devata {entity_key:$k})-[r:HAS_EPITHET]->(m) "
        "RETURN m.display_label AS l, r.knowledge_layer AS kl ORDER BY m.display_label"
    )
    axes = q(
        "MATCH (n:Devata {entity_key:$k})-[r:HAS_AXIS]->(m) "
        "RETURN m.display_label AS l, r.knowledge_layer AS kl ORDER BY m.display_label"
    )
    concepts = q(
        "MATCH (n:Devata {entity_key:$k})-[r:DEVATA_ASSOCIATED_WITH|RECEIVES_OFFERING]->(m) "
        "RETURN type(r) AS t, m.display_label AS l, r.knowledge_layer AS kl "
        "ORDER BY m.display_label"
    )
    drv.close()

    L: list[str] = []
    add = L.append
    add("% GENERATED by figures-src/fig_indra.py -- do not edit by hand.")
    add("% Queried live; selection criteria are in that script's docstring.")
    add(r"\begin{tikzpicture}[")
    add(r"  font=\footnotesize, every node/.style={align=center},")
    add(r"  hub/.style={draw=black!65, line width=0.8pt, rounded corners=3pt,")
    add(r"              fill=black!5, inner sep=6pt, font=\bfseries},")
    add(r"  nd/.style={draw=black!40, rounded corners=2pt, inner sep=3pt,")
    add(r"             font=\scriptsize, fill=white, line width=0.4pt},")
    add(r"  l1/.style={nd, fill=SkyBlue!22, draw=SkyBlue!70!black},")
    add(r"  l2/.style={nd, fill=SkyBlue!10, draw=SkyBlue!45!black},")
    add(r"  l3/.style={nd, fill=RoyalBlue!30, draw=RoyalBlue!75!black},")
    add(r"  l4/.style={nd, fill=RoyalBlue!12, draw=RoyalBlue!55!black},")
    add(r"  e/.style={-{Latex[length=1.5mm,width=1.1mm]}, draw=black!45,")
    add(r"            line width=0.45pt},")
    add(r"  el/.style={font=\tiny\itshape, text=black!60, inner sep=1.2pt,")
    add(r"             fill=white},")
    add(r"  sec/.style={font=\scriptsize\bfseries, text=black!55},")
    add(r"]")
    add(r"\node[hub] (indra) at (0,0) {Indra\\[-1pt]\scriptsize\mdseries"
        r" \code{VG:DEVATA:INDRAH}};")

    # ---- L1 quadrant: what a source states, upper left ----------------
    add(r"\node[sec, anchor=west] at (-7.4,3.35) {\textsc{l1} --- a source states it};")
    y = 2.7
    for i, row in enumerate(r for r in agg if r["kl"] == "L1_SOURCE_EXPLICIT"):
        lab = row["t"].replace("_", r"\_")
        prec = str(row["ap"]).replace("_", r"\_")
        add(
            f"\\node[l1] (a{i}) at (-4.9,{y:.2f}) "
            f"{{{thou(row['n'])} passages\\\\[-2pt]\\code{{{lab}}}"
            f"\\\\[-2pt]\\tiny {prec}}};"
        )
        add(f"\\draw[e] (a{i}) -- (indra);")
        y -= 1.35
    for i, row in enumerate(c for c in concepts if c["kl"] == "L1_SOURCE_EXPLICIT"):
        add(
            f"\\node[l1] (c1{i}) at (-4.9,{y:.2f}) "
            f"{{{tex(row['l'])}\\\\[-2pt]\\tiny \\code{{{row['t'].replace('_', chr(92)+'_')}}}}};"
        )
        add(f"\\draw[e] (indra) -- (c1{i});")
        y -= 1.05

    # ---- L2 quadrant: reproducible derivation, upper right ------------
    add(r"\node[sec, anchor=east] at (7.4,3.35) "
        r"{\textsc{l2} --- reproducibly derived};")
    y = 2.7
    for i, row in enumerate(r for r in agg if STYLE.get(str(r["kl"])) == "l2"):
        lab = row["t"].replace("_", r"\_")
        prec = str(row["ap"]).replace("_", r"\_")
        add(
            f"\\node[l2] (b{i}) at (4.9,{y:.2f}) "
            f"{{{thou(row['n'])} passages\\\\[-2pt]\\code{{{lab}}}"
            f"\\\\[-2pt]\\tiny {prec}}};"
        )
        add(f"\\draw[e] (b{i}) -- (indra);")
        y -= 1.35
    names = ", ".join(tex(str(r["l"])) for r in cooc)
    add(
        f"\\node[l2] (cooc) at (4.9,{y:.2f}) [text width=44mm] "
        f"{{top co-occurring deities by lift\\\\[-2pt]\\tiny {names}}};"
    )
    add(r"\draw[e] (indra) -- (cooc);")
    y -= 1.25
    anames = ", ".join(tex(str(r["l"])) for r in acts)
    add(
        f"\\node[l2] (acts) at (4.9,{y:.2f}) [text width=44mm] "
        f"{{\\code{{PERFORMS\\_ACTION}}\\\\[-2pt]\\tiny {anames}}};"
    )
    add(r"\draw[e] (indra) -- (acts);")

    # ---- L3: model-extracted, lower right ------------------------------
    add(r"\node[sec, anchor=east] at (7.4,-3.65) "
        r"{\textsc{l3} --- a model proposed it};")
    m = next((a for a in assertions if a["der"] == "MODEL_EXTRACTION"), None)
    n_model = m["n"] if m else 0
    det = sum(a["n"] for a in assertions if a["der"] != "MODEL_EXTRACTION")
    add(
        f"\\node[l3] (l3) at (4.9,-4.55) [text width=44mm] "
        f"{{{n_model} semantic assertions name Indra as agent\\\\[-2pt]"
        f"\\tiny \\code{{derivation=MODEL\\_EXTRACTION}}, beside {det} derived "
        f"deterministically}};"
    )
    add(r"\draw[e] (l3) -- (indra);")

    # ---- L4: interpretive, lower left ----------------------------------
    add(r"\node[sec, anchor=west] at (-7.4,-2.95) "
        r"{\textsc{l4} --- an interpretive reading};")
    enames = ", ".join(tex(str(r["l"])) for r in epith)
    add(
        f"\\node[l4] (ep) at (-4.9,-3.95) [text width=44mm] "
        f"{{{len(epith)} epithets\\\\[-2pt]\\tiny {enames}}};"
    )
    add(r"\draw[e] (indra) -- (ep);")
    xnames = ", ".join(tex(str(r["l"])) for r in axes)
    add(
        f"\\node[l4] (ax) at (-4.9,-5.55) [text width=44mm] "
        f"{{{len(axes)} deity axes\\\\[-2pt]\\tiny {xnames}}};"
    )
    add(r"\draw[e] (indra) -- (ax);")
    l4c = [c for c in concepts if c["kl"] == "L4_INTERPRETIVE_CLAIM"]
    if l4c:
        cn = ", ".join(tex(str(r["l"])) for r in l4c)
        add(
            f"\\node[l4] (c4) at (-4.9,-6.85) [text width=44mm] "
            f"{{\\code{{DEVATA\\_ASSOCIATED\\_WITH}}\\\\[-2pt]\\tiny {cn}}};"
        )
        add(r"\draw[e] (indra) -- (c4);")

    add(
        r"\node[font=\scriptsize\itshape, text=black!55, text width=14.2cm,"
        r" align=left] at (0,-8.45) {The split inside \code{HAS\_DEVATA} is the"
        r" point: the same predicate reaches this deity both as a per-passage"
        r" statement and as a label inherited from the enclosing hymn, and only"
        r" \code{attribution\_precision} tells them apart. A reader who counts"
        r" ``Indra's verses'' from this predicate alone reports 2{,}869 where the"
        r" source states 655.};"
    )
    add(r"\end{tikzpicture}")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    print("wrote " + str(OUT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
