"""Emit the manuscript's numeric tables as LaTeX, read from fact_freeze.json.

Every table written here is a projection of the frozen fact set, so a table and the
prose that cites it cannot disagree unless the freeze itself is stale. Tables that
carry judgement rather than measurement (the responsibility matrix, the failure
ledger) are authored by hand in tables/ and are not generated here.

    python figures-src/make_tables.py
"""

from __future__ import annotations

import json
from pathlib import Path

BASE = Path(__file__).resolve().parents[1]
FREEZE = BASE / "supplementary" / "fact_freeze.json"
OUT = BASE / "tables"

RECENSION = {
    "RV": ("\\d{R}gveda", "\\'S\\=akala"),
    "SV": ("S\\=amaveda", "Kauthuma \\=Arcika"),
    "YV": ("Yajurveda (\\'Sukla)", "V\\=ajasaneyi M\\=adhyandina"),
    "AV": ("Atharvaveda", "\\'Saunaka"),
}
EXCLUDED_GLOSS = {
    "RV": "no second recension; no Padap\\=a\\d{t}ha; no Br\\=ahma\\d{n}a, "
          "\\=Ara\\d{n}yaka or Upani\\d{s}ad",
    "SV": "\\emph{\\=arcika} only --- all four \\iast{g\\=ana} collections excluded; "
          "no second recension",
    "YV": "\\'Sukla only --- the entire Kr\\d{s}\\d{n}a Yajurveda absent; no K\\=a\\d{n}va; "
          "no \\'Satapatha",
    "AV": "\\'Saunaka only --- Paippal\\=ada absent; no Gopatha Br\\=ahma\\d{n}a",
}
TIER_LABEL = {
    "L1_SOURCE_EXPLICIT": "\\Lone",
    "L2_DETERMINISTIC_DERIVED": "\\Ltwo",
    "L3_LLM_EXTRACTED": "\\Lthree",
    "L4_INTERPRETIVE_CLAIM": "\\Lfour",
    "UNLABELLED": "untyped (a recorded defect)",
}
TIER_GLOSS = {
    "L1_SOURCE_EXPLICIT": "a source states it",
    "L2_DETERMINISTIC_DERIVED": "a reproducible rule over stored text or over \\vocab{l1}",
    "L3_LLM_EXTRACTED": "a language model read evidence and proposed it",
    "L4_INTERPRETIVE_CLAIM": "a reading held by this project or a named commentator",
    "UNLABELLED": "no layer recorded; see \\cref{sec:threats}",
}
TIER_ORDER = list(TIER_LABEL)


def n(x: float) -> str:
    return f"{int(round(x)):,}".replace(",", "{,}")


def pct(x: float, d: int = 2) -> str:
    return f"{x:.{d}f}"


def write(name: str, body: str) -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / name).write_text(body, encoding="utf-8")
    print("wrote tables/" + name)


def t_corpus(f: dict) -> None:
    m = f["corpus"]["mantras_by_work"]
    tr = f["translation"]["mantras_with_translation_by_work"]
    rows = []
    for k in ("RV", "AV", "YV", "SV"):
        work, rec = RECENSION[k]
        cov = 100.0 * tr.get(k, 0) / m[k]
        rows.append(
            f"{work} & {rec} & {n(m[k])} & {n(tr.get(k, 0))} & {pct(cov, 1)} & "
            f"\\footnotesize {EXCLUDED_GLOSS[k]} \\\\"
        )
    total = f["corpus"]["mantras_total"]
    tot_tr = sum(tr.values())
    body = r"""% generated by figures-src/make_tables.py -- do not edit
\begin{table}[tb]
\centering
\caption{The canonical corpus. Each work is one recension of one Veda; the scope
limits in the last column are stored as queryable properties on the \code{Work} node,
not only as prose. ``Rendered'' counts mantras reachable from at least one
\code{Translation} node, which for the S\=amaveda means reused \d{R}gvedic renderings
rather than S\=amavedic translations (\cref{sec:translation}).}
\label{tab:corpus}
\small
\begin{tabularx}{\linewidth}{@{}llrrr>{\raggedright\arraybackslash}X@{}}
\toprule
Work & Recension & Mantras & Rendered & \% & Explicitly not held \\
\midrule
""" + "\n".join(rows) + r"""
\midrule
\textbf{Total} & & \textbf{""" + n(total) + r"""} & \textbf{""" + n(tot_tr) + r"""}
& \textbf{""" + pct(100.0 * tot_tr / total, 1) + r"""} & \\
\bottomrule
\end{tabularx}
\end{table}
"""
    write("corpus.tex", body)


def t_layers(f: dict) -> None:
    fold = f["epistemic"]["relationship_knowledge_layer_folded"]
    p = f["epistemic"]["relationship_knowledge_layer_pct"]
    rows = [
        f"{TIER_LABEL[k]} & \\footnotesize {TIER_GLOSS[k]} & {n(fold[k])} & {pct(p[k])} \\\\"
        for k in TIER_ORDER
        if k in fold
    ]
    body = r"""% generated by figures-src/make_tables.py -- do not edit
\begin{table}[tb]
\centering
\caption{Relationships by epistemic layer, measured on the live graph at
\code{6bf220c}. The layer is a stored, indexed edge property, so this distribution is
a query rather than an estimate. Two pipeline generations wrote the field with and
without the \code{L}-prefix; the legacy spellings are folded here and reported
unfolded in the fact freeze.}
\label{tab:layers}
\small
\begin{tabularx}{\linewidth}{@{}l>{\raggedright\arraybackslash}Xrr@{}}
\toprule
Layer & Meaning & Edges & \% \\
\midrule
""" + "\n".join(rows) + r"""
\midrule
\textbf{Total} & & \textbf{""" + n(f["graph"]["relationships_total"]) + r"""}
& \textbf{100.00} \\
\bottomrule
\end{tabularx}
\end{table}
"""
    write("layers.tex", body)


def t_reuse(f: dict) -> None:
    mx = f["connections"]["cross_work_matrix"]
    pairs = ["RV", "SV", "YV", "AV"]
    order = ["EXACT_PARALLEL_OF", "NEAR_PARALLEL_OF", "VARIANT_OF", "REUSES_TEXT_FROM"]
    label = {
        "EXACT_PARALLEL_OF": "\\code{EXACT\\_PARALLEL\\_OF}",
        "NEAR_PARALLEL_OF": "\\code{NEAR\\_PARALLEL\\_OF}",
        "VARIANT_OF": "\\code{VARIANT\\_OF}",
        "REUSES_TEXT_FROM": "\\code{REUSES\\_TEXT\\_FROM}",
    }
    lines = []
    for rel in order:
        cells = mx.get(rel, {})
        tot = sum(cells.values())
        seen = sorted(cells.items(), key=lambda kv: -kv[1])
        detail = ", ".join(
            f"{k.replace('->', '$\\to$')}~{n(v)}" for k, v in seen
        )
        lines.append(f"{label[rel]} & {n(tot)} & \\footnotesize {detail} \\\\")
    body = r"""% generated by figures-src/make_tables.py -- do not edit
\begin{table}[tb]
\centering
\caption{Cross-textual relationships between mantras, by predicate and work pair.
The four predicates are deliberately not collapsed into one ``similar to'': they
assert different things, and the strongest, \code{REUSES\_TEXT\_FROM}, is directed only
where a tradition states the direction (\cref{sec:reuse}). Pairs are shown as
source~$\to$~target.}
\label{tab:reuse}
\small
\begin{tabularx}{\linewidth}{@{}lr>{\raggedright\arraybackslash}X@{}}
\toprule
Predicate & Edges & By work pair \\
\midrule
""" + "\n".join(lines) + r"""
\bottomrule
\end{tabularx}
\end{table}
"""
    write("reuse.tex", body)


def t_labels(f: dict) -> None:
    labels = list(f["graph"]["node_labels"].items())
    rels = list(f["graph"]["relationship_types"].items())
    k = 14
    rows = []
    for i in range(k):
        la = f"\\code{{{labels[i][0]}}} & {n(labels[i][1])}" if i < len(labels) else " & "
        rl = (
            f"\\code{{{rels[i][0].replace('_', chr(92) + '_')}}} & {n(rels[i][1])}"
            if i < len(rels)
            else " & "
        )
        rows.append(f"{la} & {rl} \\\\")
    body = r"""% generated by figures-src/make_tables.py -- do not edit
\begin{table}[tb]
\centering
\caption{The fourteen largest node labels and relationship types, of """ + str(
        f["graph"]["node_labels_in_use"]
    ) + r""" labels
in use and """ + str(f["graph"]["relationship_types_in_use"]) + r""" relationship types.
A further label, \code{SourceArtifact}, is declared in the store's token table but
carries no nodes.}
\label{tab:labels}
\small
\begin{tabular}{@{}lr@{\hskip 2em}lr@{}}
\toprule
Node label & Nodes & Relationship type & Edges \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table}
"""
    write("labels.tex", body)


def t_samaveda(f: dict) -> None:
    s = f["samaveda_notation"]
    d = s["disposition"]
    w = s["withheld_classes"]
    rows = [
        f"notation present, source-explicit & {n(d.get('SOURCE_EXPLICIT_PRESENT', 0))} "
        "& \\footnotesize the witness prints marks on this verse \\\\",
        f"\\quad withheld: near line, witness disagreement & "
        f"{n(w.get('NEAR_LINE_EXISTS_WITNESS_DISAGREEMENT', 0))} "
        "& \\footnotesize needs philological adjudication \\\\",
        f"\\quad withheld: no near line, probable absence & "
        f"{n(w.get('NO_NEAR_LINE_PROBABLE_ABSENCE', 0))} "
        "& \\footnotesize the witness may not carry the verse \\\\",
        f"\\quad withheld: occurrence consumed by a repeat & "
        f"{n(w.get('WITNESS_OCCURRENCE_CONSUMED_BY_A_COREFERENT_REPEAT', 0))} "
        "& \\footnotesize \\textbf{added by Gate C} (\\cref{sec:case-samaveda}) \\\\",
    ]
    body = r"""% generated by figures-src/make_tables.py -- do not edit
\begin{table}[tb]
\centering
\caption{S\=amavedic notation: every one of the """ + n(
        sum(d.values())
    ) + r""" \=Arcika verses carries
exactly one typed disposition, so a reader can never mistake a withheld verse for a
verse the tradition does not notate. The third withheld class did not exist until an
adversarial gate falsified the stated reasons of 39 rows.}
\label{tab:samaveda}
\small
\begin{tabularx}{\linewidth}{@{}lr>{\raggedright\arraybackslash}X@{}}
\toprule
Disposition & Verses & \\
\midrule
""" + "\n".join(rows) + r"""
\midrule
\textbf{Total} & \textbf{""" + n(sum(d.values())) + r"""}
& \footnotesize verses with no disposition at all: \textbf{0} \\
\bottomrule
\end{tabularx}
\end{table}
"""
    write("samaveda.tex", body)


def t_gaps(f: dict) -> None:
    g = f["gap_registry"]["by_status"]
    closed = sum(v for k, v in g.items() if k.startswith("CLOSED"))
    rows = [
        f"\\code{{{k.replace('_', chr(92) + '_')}}} & {n(v)} \\\\"
        for k, v in g.items()
    ]
    body = r"""% generated by figures-src/make_tables.py -- do not edit
\begin{table}[tb]
\centering
\caption{The gap registry at \code{6bf220c}. Until a late campaign the registry had
no closed state at all, so every gate could be green while completeness was
unresolvable (\cref{sec:failure}); the closure vocabulary below was added to make
termination expressible.}
\label{tab:gaps}
\small
\begin{tabular}{@{}lr@{}}
\toprule
Status & Entries \\
\midrule
""" + "\n".join(rows) + r"""
\midrule
\textbf{Total} & \textbf{""" + n(f["gap_registry"]["entries"]) + r"""} \\
\multicolumn{2}{@{}l}{\footnotesize of which closed by some route: \textbf{""" + n(
        closed
    ) + r"""}} \\
\bottomrule
\end{tabular}
\end{table}
"""
    write("gaps.tex", body)



COVERAGE_ORDER = [
    ("DEDICATED_TRANSLATION", "its own 1:1 English rendering"),
    ("RANGE_TRANSLATION_ANCHOR", "anchors a print unit spanning it and others"),
    ("RANGE_COVERED", "carries no edge; named in another verse's span"),
    ("CONTAINER_TRANSLATION", "only rendering is aligned to a hymn"),
    ("REUSED_RENDERING", "another corpus's rendering of identical Sanskrit"),
    (
        "UNCOVERED_REUSABLE_PARALLEL_AVAILABLE",
        "nothing reaches it, but a translated identical parallel exists",
    ),
    ("UNCOVERED_NO_RENDERING_REACHES_IT", "nothing reaches it, and no parallel does"),
]


def t_coverage(f: dict) -> None:
    cells = f["translation"]["verse_coverage_state"]
    tot = f["translation"]["verse_coverage_state_totals"]
    mant = f["corpus"]["mantras_by_work"]
    works = ("RV", "AV", "YV", "SV")
    bs = chr(92)
    rows = []
    for key, gloss in COVERAGE_ORDER:
        if key not in tot:
            continue
        name = bs + "code{" + key.replace("_", bs + "_") + "}"
        vals = " & ".join(n(cells.get(key + "|" + w, 0)) for w in works)
        rows.append(name + " & " + vals + " & " + n(tot[key]) + r" \\")
        rows.append(
            r" & \multicolumn{5}{@{}l@{}}{\footnotesize " + gloss + r"} \\[2pt]"
        )
    grand = sum(tot.values())
    totals = " & ".join(r"\textbf{" + n(mant[w]) + "}" for w in works)
    body = (
        "% generated by figures-src/make_tables.py -- do not edit\n"
        "\\begin{table}[tb]\n\\centering\n"
        "\\caption{Translation coverage as a typed state rather than a boolean. Each "
        "of the " + n(grand) + " mantras carries exactly one terminal state, so an "
        "absence always arrives with its reason attached. The two \\code{UNCOVERED} "
        "states are distinct on purpose: one says a translated identical parallel "
        "exists elsewhere in the corpus, the other says nothing reaches the verse at "
        "all. The S\\=amavedic column is the reason the distinction was built.}\n"
        "\\label{tab:coverage}\n\\small\n"
        "\\begin{tabular}{@{}lrrrrr@{}}\n\\toprule\n"
        "Verse coverage state & RV & AV & YV & SV & Total \\\\\n\\midrule\n"
        + "\n".join(rows) + "\n\\midrule\n"
        "\\textbf{Total} & " + totals + " & \\textbf{" + n(grand) + "} \\\\\n"
        "\\bottomrule\n\\end{tabular}\n\\end{table}\n"
    )
    write("coverage.tex", body)


def main() -> int:
    f = json.loads(FREEZE.read_text(encoding="utf-8"))
    t_corpus(f)
    t_layers(f)
    t_reuse(f)
    t_labels(f)
    t_samaveda(f)
    t_gaps(f)
    t_coverage(f)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
