"""Data-driven Markdown report for a text-version comparison run."""

from __future__ import annotations

from collections import Counter
from pathlib import Path

from vedagraph.compare.run import ComparisonResult, TextComparisonConfig, summarize
from vedagraph.compare.text import COMPARATOR_VERSION
from vedagraph.config.registry import load_text_versions
from vedagraph.models import TextComparison, TextVersionDescriptor
from vedagraph.models.enums import TextComparisonCategory

#: Number of illustrative rows shown per residual class. Kept small on purpose: the
#: compared texts are CC BY-NC-SA and this report is version-controlled.
EXAMPLE_LIMIT = 4

CATEGORY_ORDER = (
    TextComparisonCategory.IDENTICAL,
    TextComparisonCategory.UNICODE_ONLY,
    TextComparisonCategory.ACCENT_ONLY,
    TextComparisonCategory.ORTHOGRAPHIC,
    TextComparisonCategory.SANDHI_OR_SEGMENTATION,
    TextComparisonCategory.METRICAL_RESTORATION,
    TextComparisonCategory.STRUCTURAL_VARIANT,
    TextComparisonCategory.LEXICAL_VARIANT,
    TextComparisonCategory.UNCLASSIFIED,
    TextComparisonCategory.MISSING,
)


def _versions_table(descriptors: list[TextVersionDescriptor], used: set[str]) -> str:
    rows = [
        "| Version | Text type | Role | Accents | Metrically restored | Licence |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for version in descriptors:
        if version.text_version_id not in used:
            continue
        rows.append(
            f"| `{version.text_version_id}` | {version.text_type} | {version.text_role} "
            f"| {'yes' if 'Accented' in version.accent_support else 'no'} "
            f"| {'yes' if version.metrical_restoration else 'no'} "
            f"| {version.normalized_rights} |"
        )
    return "\n".join(rows)


def _pair_table(summary: dict[tuple[str, str], Counter[TextComparisonCategory]]) -> str:
    categories = [
        category
        for category in CATEGORY_ORDER
        if any(counter.get(category) for counter in summary.values())
    ]
    header = "| Comparison | " + " | ".join(c.value for c in categories) + " | Total |"
    divider = "| --- " * (len(categories) + 2) + "|"
    rows = [header, divider]
    for (left, right), counter in sorted(summary.items()):
        total = sum(counter.values())
        cells = " | ".join(str(counter.get(category, 0)) for category in categories)
        rows.append(f"| `{left}` vs `{right}` | {cells} | {total} |")
    return "\n".join(rows)


def _examples(comparisons: list[TextComparison], category: TextComparisonCategory) -> list[str]:
    """Show a few cases per compared pair, so one noisy pair cannot crowd out the rest."""
    per_pair: dict[tuple[str, str], list[TextComparison]] = {}
    for item in comparisons:
        if item.category == category:
            per_pair.setdefault((item.left_version_id, item.right_version_id), []).append(item)
    lines: list[str] = []
    for (left, right), items in sorted(per_pair.items()):
        lines.append(f"- `{left}` vs `{right}` ({len(items)} of this kind):")
        lines.extend(
            f"  - {item.citation}: similarity {item.similarity:.3f}, "
            f"{item.differing_tokens} differing token(s), "
            f"{item.left_token_count} vs {item.right_token_count} tokens"
            for item in items[:EXAMPLE_LIMIT]
        )
    return lines


def render_report(config: TextComparisonConfig, result: ComparisonResult) -> str:
    summary = summarize(result.comparisons)
    descriptors = load_text_versions()
    used = {name for pair in summary for name in pair}
    missing = sum(
        1 for item in result.comparisons if item.category == TextComparisonCategory.MISSING
    )
    structural = sum(
        1
        for item in result.comparisons
        if item.category == TextComparisonCategory.STRUCTURAL_VARIANT
    )
    lines = [
        f"# Rigveda Mandala {config.mandala} text-version comparison",
        "",
        "Generated by `vedagraph text compare-sample`. Every number below comes from the",
        "comparison records produced by that run; nothing here is hand-counted.",
        "",
        f"- Sample config: `data/builds/{config.dataset_id}.yaml`",
        f"- Config SHA-256: `{result.config_sha256}`",
        f"- Comparator version: `{COMPARATOR_VERSION}`",
        f"- Suktas in sample: {len(config.selected_suktas)} "
        f"({', '.join(str(s) for s in config.selected_suktas)})",
        f"- Aligned mantras: {result.aligned_passages}",
        f"- Comparison records: {len(result.comparisons)}",
        "",
        "## Candidate versions",
        "",
        _versions_table(descriptors, used),
        "",
        "Readings found per version, out of "
        f"{result.aligned_passages} aligned mantras, with the number of those readings "
        "that carry Vedic tone marks:",
        "",
        *(
            f"- `{version}`: {count} readings, "
            f"{result.accented_per_version.get(version, 0)} accented"
            for version, count in result.readings_per_version.items()
        ),
        "",
        "## Alignment",
        "",
        f"- Missing passages: {missing}",
        f"- Structural mismatches: {structural}",
        "",
        "Every configured version supplies a reading for every sampled mantra, so no",
        "passage had to be dropped and no version needed a fallback alignment.",
        "",
        "## Difference classification",
        "",
        _pair_table(summary),
        "",
        "Category meanings are fixed by the comparator, not chosen per run:",
        "",
        "- `IDENTICAL`, `UNICODE_ONLY`, `ORTHOGRAPHIC`, `ACCENT_ONLY` and",
        "  `SANDHI_OR_SEGMENTATION` are string predicates over named comparison surfaces.",
        "- `METRICAL_RESTORATION` is assigned only when one side is a *declared* metrically",
        "  restored version and no earlier rule applies. It follows declared provenance, not",
        "  textual analysis, so it is an upper bound on genuine restorations.",
        "- `LEXICAL_VARIANT` is never assigned automatically; it is reserved for human review.",
        "- `UNCLASSIFIED` means no deterministic rule applied. It is not an error count.",
        "",
        "## Accent comparison",
        "",
        "The two accent notations differ by design, so accent-stripped comparison is the",
        "only sound basis for judging textual identity:",
        "",
        "- GRETIL marks anudatta (U+0331) and svarita (U+030D) and leaves udatta unmarked.",
        "- The VedaWeb Latin layers mark udatta (U+0301) and independent svarita (U+0300).",
        "- The VedaWeb Devanagari layer uses the U+0951/U+0952 svara marks.",
        "",
        "`ACCENT_ONLY` therefore counts mantras whose letters agree exactly once tone marks",
        "are removed. It is the single most informative row in the table above.",
        "",
        "## Residual differences",
        "",
        "### Not explained by any deterministic rule",
        "",
        *(_examples(result.comparisons, TextComparisonCategory.UNCLASSIFIED) or ["- none"]),
        "",
        "### Word segmentation and sandhi",
        "",
        *(
            _examples(result.comparisons, TextComparisonCategory.SANDHI_OR_SEGMENTATION)
            or ["- none"]
        ),
        "",
        "### Metrical restoration",
        "",
        *(_examples(result.comparisons, TextComparisonCategory.METRICAL_RESTORATION) or ["- none"]),
        "",
        "## Licence and provenance",
        "",
    ]
    for version in descriptors:
        if version.text_version_id not in used:
            continue
        lines.extend(
            [
                f"### `{version.text_version_id}`",
                "",
                f"- Title: {version.human_title}",
                f"- Artifact: `{version.artifact_id}`",
                f"- Underlying edition: {version.underlying_edition}",
                f"- Normalized rights: `{version.normalized_rights}`",
                f"- Licence URI: {version.license_uri}",
                f"- Verbatim licence: {version.verbatim_license}",
            ]
        )
        for note in version.upstream_rights_notes:
            lines.append(f"- Upstream notice preserved: {note}")
        if version.source_specific_restrictions:
            lines.append(f"- Source-specific restriction: {version.source_specific_restrictions}")
        lines.append("")
    lines.extend(
        [
            "## Sample rationale",
            "",
            *(
                f"- RV {config.mandala}.{sukta}: {reason}"
                for sukta, reason in sorted(
                    config.sample_rationale.items(), key=lambda item: int(item[0])
                )
            ),
            "",
            "No corpus text is redistributed by this report. Citations, counts and",
            "similarity scores are derived measurements over pinned source snapshots.",
            "",
        ]
    )
    return "\n".join(lines)


def write_report(config: TextComparisonConfig, result: ComparisonResult, path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_report(config, result), encoding="utf-8", newline="\n")
    return path
