"""Generate the committed human-readable knowledge-layer reports.

Everything here is derived from the built knowledge layer and the committed registries.
No bulk Sanskrit text is reproduced: the reports carry aggregates, entity keys, labels
and minimal citation examples only.
"""

from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path

from vedagraph.knowledge.build import build_knowledge, load_artifact_index
from vedagraph.knowledge.compare import compare_with_vhp, vedaweb_addressees
from vedagraph.knowledge.normalize import ascii_key
from vedagraph.knowledge.stats import build_stats
from vedagraph.models.enums import KnowledgeEntityType
from vedagraph.models.knowledge import KnowledgeEntity

CORPUS = Path("data/canonical/rigveda_full_v1")
ARTIFACTS = Path("data/derived/wsc2023_anukramani_artifacts.json")
KNOWLEDGE = Path("data/knowledge/rigveda_deterministic_v1")
REPORTS = Path("docs/reports")
VEDAWEB_TEI = Path("data/raw/vedaweb/2026-09-04")

REGISTRY_REPORTS = {
    KnowledgeEntityType.RISHI: ("RIGVEDA_RISHI_REGISTRY.md", "Ṛṣi"),
    KnowledgeEntityType.DEVATA: ("RIGVEDA_DEVATA_REGISTRY.md", "Devatā"),
    KnowledgeEntityType.CHANDAS: ("RIGVEDA_CHANDAS_REGISTRY.md", "Chandas"),
}

COVERAGE_HEADERS = [
    "Predicate",
    "Mantras resolved",
    "%",
    "Claimed but unresolved",
    "No claim",
    "Multiple entities",
    "Assertions",
    "Distinct entities",
]

UNRESOLVED_HEADERS = [
    "Raw label",
    "Normalized",
    "Status",
    "Occurrences",
    "Mantras",
    "Examples",
    "Candidates",
    "Reason",
]

NOT_A_MENTION = (
    "**An assignment is not a textual mention.** `HAS_DEVATA: agniḥ` records that the "
    "traditional index assigns Agni as the devatā of that mantra. It does not claim that "
    "the word *agni* occurs in the Sanskrit. Literal occurrence will be a separate "
    "`MENTIONS_ENTITY` predicate produced by a later deterministic lexical phase."
)


def _table(headers: list[str], rows: list[list[str]]) -> str:
    lines = ["| " + " | ".join(headers) + " |", "| " + " | ".join("---" for _ in headers) + " |"]
    lines.extend("| " + " | ".join(row) + " |" for row in rows)
    return "\n".join(lines)


def _suspected_duplicates(entities: list[KnowledgeEntity]) -> list[list[str]]:
    """Registered entities whose labels differ only in diacritics. Never auto-merged."""
    grouped: dict[str, list[KnowledgeEntity]] = defaultdict(list)
    for entity in entities:
        grouped[ascii_key(entity.preferred_label)].append(entity)
    return [
        [slug, ", ".join(f"`{item.entity_key}` ({item.preferred_label})" for item in members)]
        for slug, members in sorted(grouped.items())
        if len(members) > 1
    ]


def main() -> None:
    artifacts = load_artifact_index(ARTIFACTS)
    result = build_knowledge(corpus_dir=CORPUS, artifacts=artifacts)
    stats = build_stats(result, top=25)
    manifest = json.loads((KNOWLEDGE / "manifest.json").read_text(encoding="utf-8"))
    comparisons = compare_with_vhp(CORPUS, result.source_assertions, result.corpus)
    REPORTS.mkdir(parents=True, exist_ok=True)

    _write_build_report(result, stats, manifest)
    for entity_type, (filename, label) in REGISTRY_REPORTS.items():
        _write_registry_report(entity_type, filename, label, result, stats)
    _write_comparison_report(result, comparisons)
    print("wrote 5 reports to docs/reports")


def _write_build_report(result, stats, manifest) -> None:  # type: ignore[no-untyped-def]
    mismatches = len(result.alignment.verse_count_mismatches)
    coverage_rows = [
        [
            f"`{item.predicate.value}`",
            f"{item.mantras_resolved:,}",
            f"{item.mantras_resolved / item.total_mantras:.2%}",
            f"{item.mantras_unresolved_only:,}",
            f"{item.mantras_without_claim:,}",
            f"{item.mantras_with_multiple_entities:,}",
            f"{item.assertion_count:,}",
            f"{item.distinct_entities:,}",
        ]
        for item in stats.coverage
    ]
    qa_rows = sorted(
        {(issue.check_id, issue.severity.value) for issue in result.qa_issues},
    )
    counts: dict[tuple[str, str], int] = defaultdict(int)
    for issue in result.qa_issues:
        counts[(issue.check_id, issue.severity.value)] += 1

    qa_table = (
        _table(
            ["Check", "Severity", "Count"],
            [
                [f"`{check}`", severity, str(counts[(check, severity)])]
                for check, severity in qa_rows
            ],
        )
        if qa_rows
        else "No issues."
    )
    coverage_table = _table(COVERAGE_HEADERS, coverage_rows)
    body = f"""# Rigveda deterministic knowledge build

Generated by `scripts/generate_knowledge_reports.py`. Manifest
`{manifest["version"]}` over corpus `{manifest["corpus_version"]}`.

Source: the commit-pinned digital Rigvedic Anukramaṇī of Akavarapu and Bhattacharya
(2023), repository `{manifest["source_repository_url"]}` at commit
`{manifest["source_commit_sha"]}`. No language model, embedding, or classifier
participates at any stage; the repository's own devatā classifier and word vectors are
deliberately not ingested. See
[`RIGVEDA_ANUKRAMANI_SOURCE.md`](../architecture/RIGVEDA_ANUKRAMANI_SOURCE.md).

{NOT_A_MENTION}

## Alignment to the canonical corpus

| Measure | Value |
| --- | ---: |
| Dataset rows (one per Sūkta) | {stats.dataset_rows:,} |
| Rows aligned to a corpus Sūkta | {stats.aligned_rows:,} |
| Unaligned rows | {stats.unaligned_rows:,} |
| Duplicate row mappings | {stats.duplicate_row_mappings:,} |
| Corpus Sūktas the dataset does not name | {stats.total_suktas - stats.aligned_rows:,} |
| Declared verse counts disagreeing with the corpus | {mismatches:,} |
| Corpus Sūktas | {stats.total_suktas:,} |
| Corpus mantras | {stats.total_mantras:,} |

Every one of the {stats.dataset_rows:,} rows names a Sūkta that exists in the corpus, and
every row's declared verse count equals the corpus mantra count for that Sūkta. The
dataset is therefore an independent structural witness to the 1,028 / 10,552 shape as
well as a metadata source.

## Assertion counts

| Layer | Records |
| --- | ---: |
| Anukramaṇī staging rows | {stats.dataset_rows:,} |
| Metadata source assertions (raw, scoped, unresolved) | {stats.source_assertions:,} |
| Deterministic knowledge assertions (mantra → entity) | {stats.knowledge_assertions:,} |

## Coverage

{coverage_table}

## Canonical entities

| Type | Entities |
| --- | ---: |
| Ṛṣi | {stats.entity_counts["RISHI"]:,} |
| Devatā | {stats.entity_counts["DEVATA"]:,} |
| Chandas | {stats.entity_counts["CHANDAS"]:,} |
| Composite Devatā labels preserved whole | {stats.composite_devata_count:,} |

Unresolved labels: {stats.unresolved_label_counts or "none"}.

## QA

Status **{result.qa_status.value}**.

{qa_table}

## Provenance chain

```text
answer
  → knowledge assertion (mantra key, predicate, entity key)
  → source assertion   (raw label, scope, source locator)
  → pinned artifact    (WSC2023.RV.ANUKRAMANI.Mnn, SHA-256, commit)
  → corpus passage     (VG:RV:SAK:Mnn:Snnn:Vnnn)
```
"""
    (REPORTS / "RIGVEDA_DETERMINISTIC_KNOWLEDGE_BUILD.md").write_text(body, encoding="utf-8")


def _write_registry_report(entity_type, filename, label, result, stats) -> None:  # type: ignore[no-untyped-def]
    entities = result.entities[entity_type]
    top = {
        KnowledgeEntityType.RISHI: stats.top_rishis,
        KnowledgeEntityType.DEVATA: stats.top_devatas,
        KnowledgeEntityType.CHANDAS: stats.top_chandas,
    }[entity_type]
    unresolved = [item for item in result.unresolved if item.entity_type is entity_type]
    duplicates = _suspected_duplicates(entities)
    composites = [entity for entity in entities if entity.is_composite]
    aliased = [entity for entity in entities if entity.aliases]

    sections = [
        f"# Rigveda {label} registry",
        "",
        f"Generated from `data/registry/{entity_type.value.lower()}s.yaml`"
        if entity_type is not KnowledgeEntityType.CHANDAS
        else "Generated from `data/registry/chandas.yaml`",
        "and the built knowledge layer. Entity keys are pinned identity.",
        "",
        NOT_A_MENTION,
        "",
        "## Summary",
        "",
        f"| Measure | Value |\n| --- | ---: |\n"
        f"| Canonical entities | {len(entities):,} |\n"
        f"| Entities with a reviewed alias | {len(aliased):,} |\n"
        f"| Composite (hyphen-joined) labels | {len(composites):,} |\n"
        f"| Unresolved source labels | {len(unresolved):,} |\n"
        f"| Entities differing only in diacritics (not merged) | {len(duplicates):,} |",
        "",
        f"## Most frequently assigned (top {len(top)})",
        "",
        _table(
            ["Entity key", "Label", "Mantras assigned", "Sūktas"],
            [
                [
                    f"`{item.entity_key}`",
                    item.preferred_label,
                    f"{item.mantra_assignment_count:,}",
                    f"{item.sukta_count:,}",
                ]
                for item in top
            ],
        ),
    ]
    if aliased:
        sections += [
            "",
            "## Reviewed aliases",
            "",
            _table(
                ["Entity key", "Alias", "Type", "Evidence"],
                [
                    [
                        f"`{entity.entity_key}`",
                        alias.alias,
                        alias.alias_type.value,
                        (alias.evidence or "").replace("\n", " "),
                    ]
                    for entity in aliased
                    for alias in entity.aliases
                ],
            ),
        ]
    if duplicates:
        sections += [
            "",
            "## Suspected duplicates, deliberately not merged",
            "",
            "These labels share an ASCII fold. A shared fold is not evidence of identity, so"
            " each keeps its own entity and a collision-breaking key. Merging one requires an"
            " alias entry with evidence.",
            "",
            _table(["Shared fold", "Entities"], duplicates),
        ]
    if composites:
        sections += [
            "",
            "## Composite labels preserved whole",
            "",
            "The source joins several names with hyphens and states that it does not present"
            " them as a mixture of components. VedaGraph keeps the label as one entity;"
            " `HAS_COMPONENT` relations are a later, separately evidenced phase.",
            "",
            _table(
                ["Entity key", "Label", "Surface parts"],
                [
                    [
                        f"`{entity.entity_key}`",
                        entity.preferred_label,
                        ", ".join(entity.composite_parts),
                    ]
                    for entity in composites
                ],
            ),
        ]
    if entity_type is KnowledgeEntityType.DEVATA:
        classified = [
            entity
            for entity in entities
            if entity.devata_subtype and entity.devata_subtype.value != "UNKNOWN"
        ]
        sections += [
            "",
            "## Subtypes",
            "",
            f"{len(classified)} of {len(entities)} entities carry a subtype. A subtype is only"
            " set where the source paper itself classifies the label; every other entity stays"
            " `UNKNOWN` rather than being classified by inference.",
            "",
            _table(
                ["Entity key", "Label", "Subtype", "Evidence"],
                [
                    [
                        f"`{entity.entity_key}`",
                        entity.preferred_label,
                        entity.devata_subtype.value if entity.devata_subtype else "",
                        entity.notes or "",
                    ]
                    for entity in classified
                    if entity.devata_subtype is not None
                ],
            ),
        ]
    sections += [
        "",
        "## Unresolved labels",
        "",
        "None. Every source label reaches a registered entity."
        if not unresolved
        else _table(
            UNRESOLVED_HEADERS,
            [
                [
                    ", ".join(item.raw_labels),
                    item.normalized_label,
                    item.resolution_status.value,
                    str(item.occurrence_count),
                    str(item.mantra_count),
                    ", ".join(item.example_subject_keys),
                    ", ".join(f"`{key}`" for key in item.candidate_entity_keys) or "—",
                    item.reason,
                ]
                for item in unresolved
            ],
        ),
        "",
        "Registry entries are `review_status: UNREVIEWED`. They were derived deterministically"
        " from the source labels; a reader confirming them is the next human step, and the"
        " suspected-duplicate table above is where that review should start.",
        "",
    ]
    (REPORTS / filename).write_text("\n".join(sections), encoding="utf-8")


def _write_comparison_report(result, comparisons) -> None:  # type: ignore[no-untyped-def]
    counts: dict[str, int] = defaultdict(int)
    for comparison in comparisons:
        counts[comparison.agreement.value] += 1

    tei = sorted(VEDAWEB_TEI.glob("rv_book_*.tei")) or sorted(VEDAWEB_TEI.glob("*.tei"))
    addressees = vedaweb_addressees(tei)
    wsc_by_sukta: dict[tuple[int, int], set[str]] = defaultdict(set)
    for assertion in result.source_assertions:
        if assertion.predicate.value == "HAS_DEVATA":
            parts = assertion.subject_key.split(":")
            wsc_by_sukta[(int(parts[3][1:]), int(parts[4][1:]))].add(assertion.raw_value)
    sample = [
        [
            f"RV {mandala}.{sukta}",
            addressees[(mandala, sukta)][0],
            ", ".join(sorted(wsc_by_sukta.get((mandala, sukta), set()))),
        ]
        for mandala, sukta in [(1, 1), (1, 2), (1, 3), (1, 162), (2, 3), (9, 1), (10, 129)]
        if (mandala, sukta) in addressees
    ]

    body = f"""# Rigveda traditional-metadata source comparison

Generated by `scripts/generate_knowledge_reports.py`. Neither source overrides the other
anywhere in this report or in the build; a disagreement is recorded as a disagreement.

## VHP versus the digital Anukramaṇī

The VHP sample is the five reviewed Maṇḍala 1 Sūktas already in the corpus, written in
Devanagari. It is compared with the Anukramaṇī claim for the same Sūkta after
deterministic Devanagari → IAST transliteration.

| Verdict | Comparisons |
| --- | ---: |
{chr(10).join(f"| {verdict} | {count} |" for verdict, count in sorted(counts.items()))}

{
        _table(
            ["Sūkta", "Predicate", "VHP (transliterated)", "Anukramaṇī", "Verdict"],
            [
                [
                    comparison.citation,
                    f"`{comparison.predicate.value}`",
                    ", ".join(comparison.left_comparable),
                    ", ".join(comparison.right_comparable[:4]),
                    comparison.agreement.value,
                ]
                for comparison in comparisons
            ],
        )
    }

The Ṛṣi differences are a naming convention, not a factual conflict: VHP writes
*personal name + patronymic* and the Anukramaṇī writes *patronymic + personal name* with
the final sandhi that word order requires. They are classified `LABEL_DIFFERENCE` on a
declared stem-token comparison surface and are **not** merged into one entity. The two
`SOURCE_CONFLICT` rows at RV 1.191 are real: VHP gives a parenthetical designation where
the Anukramaṇī gives a composite devatā, and VHP's Ṛṣi string is written as one
sandhi-joined word on the other side.

Both readings stay in the data. Choosing between them needs a reader who knows the
notation, not a rule.

## VedaWeb hymn addressee — a different concept, not a devatā

VedaWeb's pinned TEI carries a hymn-level `dedication/addressee` in English and German
for {len(addressees):,} of the 1,028 Sūktas. This is a **modern editorial statement** of
whom a hymn addresses. It is not an Anukramaṇī devatā, it is hymn-level rather than
verse-level, and it is written in a modern language rather than Sanskrit. It is therefore
never ingested as `HAS_DEVATA`, and no string comparison between the two columns below is
meaningful.

A future layer may express the distinction as two predicates:
`TRADITIONALLY_ASSIGNED_DEVATA` (this build) and `MODERN_SCHOLARLY_ADDRESSEE` (VedaWeb).
Neither exists yet beyond this report.

{_table(["Sūkta", "VedaWeb addressee (English)", "Anukramaṇī devatā labels"], sample)}
"""
    (REPORTS / "RIGVEDA_METADATA_SOURCE_COMPARISON.md").write_text(body, encoding="utf-8")


if __name__ == "__main__":
    main()
