"""Generate safe aggregate semantic-pilot reports and the human gold worksheet."""

from __future__ import annotations

import hashlib
import json
from collections import Counter
from pathlib import Path

import yaml

from vedagraph.models.semantic import EvidencePacket, SemanticAssertionCandidate
from vedagraph.semantic.evaluate import compare_exact_parallels
from vedagraph.semantic.ontology import ALLOWED_PREDICATES, SemanticNodeType
from vedagraph.semantic.packet import build_packet, load_packet_sources

ROOT = Path("data/semantic/vedagraph-rigveda-semantic-codex-luna-pilot-1.0.0-rc1")
CONFIG = Path("data/builds/rigveda_semantic_pilot_v1.yaml")
CORPUS_DIR = Path("data/canonical/rigveda_full_v1")
KNOWLEDGE_DIR = Path("data/knowledge/rigveda_deterministic_v1")
LEXICAL_DIR = Path("data/knowledge/rigveda_lexical_v1")
REPORT_DIR = Path("docs/reports")
REVIEW_DIR = Path("docs/review")
GOLD_PATH = Path("data/gold/rigveda_semantic_gold_v1.jsonl")


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _load_jsonl(path: Path) -> list[dict[str, object]]:
    return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line]


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text.rstrip() + "\n", encoding="utf-8")


def build_worksheet() -> None:
    config = yaml.safe_load(CONFIG.read_text(encoding="utf-8"))
    rows = [row for row in config["mantras"] if row["gold"]]
    sources = load_packet_sources(
        corpus_dir=CORPUS_DIR, knowledge_dir=KNOWLEDGE_DIR, lexical_dir=LEXICAL_DIR
    )
    predicates = ", ".join(sorted(item.value for item in ALLOWED_PREDICATES))
    node_types = ", ".join(item.value for item in SemanticNodeType)
    sections: list[str] = [
        "# Rigveda semantic gold worksheet",
        "",
        "This is a human annotation worksheet, not a gold label file generated by Luna.",
        "The 120 rows remain `UNANNOTATED` until a person completes and signs them. The",
        "worksheet carries identifiers and deterministic metadata only; source text stays",
        "in the local EvidencePackets.",
        "",
        "## Reviewer instructions",
        "",
        "Review only claims supported by the supplied packet. For each proposed entity mark",
        "`ACCEPT`, `REJECT`, or `MODIFY`; for each predicate do the same. Mark explicitness",
        "as `EXPLICIT`, `STRONG_INFERENCE`, or `INTERPRETIVE`, and evidence as `VALID` or",
        "`INVALID`. Optionally record a missing expected relation. Do not infer a relation",
        "from traditional assignment alone, and do not use this worksheet to create an",
        "exhaustive philosophical reading.",
        "",
        f"Allowed predicate slots: {predicates}.",
        f"Allowed semantic node types: {node_types}.",
        "",
    ]
    for index, row in enumerate(rows, 1):
        packet = build_packet(sources, str(row["passage_key"]))
        sections.extend(
            [
                f"## {index:03d}. {row['citation']}",
                "",
                f"- Mantra ID: `{packet.passage_key}`",
                f"- Stratum: `{row['stratum']}`",
                f"- Traditional Ṛṣi: {', '.join(packet.rishi_labels) or 'none supplied'}",
                f"- Traditional Devatā: {', '.join(packet.devata_labels) or 'none supplied'}",
                f"- Traditional Chandas: {', '.join(packet.chandas_labels) or 'none supplied'}",
                "- Deterministic lexical mentions:",
            ]
        )
        if packet.mentions:
            for mention in packet.mentions:
                sections.append(
                    f"  - `{mention.entity_key}` — {mention.entity_label}; token IDs: "
                    + ", ".join(f"`{key}`" for key in mention.token_keys)
                )
        else:
            sections.append("  - none supplied")
        sections.extend(
            [
                "- Configured candidate slots: entity proposal / constrained predicate",
                "",
                "| Candidate entity | ACCEPT / REJECT / MODIFY | Node type | "
                "Evidence VALID / INVALID |",
                "|---|---|---|---|",
                "| | | | |",
                "",
                "| Predicate | ACCEPT / REJECT / MODIFY | Explicitness | "
                "Evidence VALID / INVALID |",
                "|---|---|---|---|",
                "| | | | |",
                "",
                "- Rejected tempting predicates:",
                "- Missing expected relation (optional):",
                "- Evidence notes:",
                "- Reviewer:",
                "- Review timestamp:",
                "- Status: `UNANNOTATED`",
                "",
            ]
        )
    _write(REVIEW_DIR / "RIGVEDA_SEMANTIC_GOLD_WORKSHEET.md", "\n".join(sections))


def build_reports() -> dict[str, object]:
    config = yaml.safe_load(CONFIG.read_text(encoding="utf-8"))
    pilot_rows = config["mantras"]
    candidates = _load_jsonl(ROOT / "semantic_candidates.jsonl")
    validations = _load_jsonl(ROOT / "semantic_validation.jsonl")
    payloads = _load_jsonl(ROOT / "codex_direct_payloads.jsonl")
    no_claims = sum(1 for row in payloads if not row["payload"]["assertions"])
    predicate_counts = Counter(str(row["predicate"]) for row in candidates)
    explicitness_counts = Counter(str(row["explicitness"]) for row in candidates)
    status_counts = Counter(str(row["status"]) for row in candidates)
    validation_codes = Counter(
        code for row in validations for code in row.get("codes", []) if code != "OK"
    )
    validation_rejected = sum(1 for row in validations if row["status"] == "VALIDATION_REJECTED")
    batch_stats = [
        json.loads(path.read_text(encoding="utf-8"))
        for path in sorted(ROOT.glob("batches/batch_*/stats.json"))
    ]

    sources = load_packet_sources(
        corpus_dir=CORPUS_DIR, knowledge_dir=KNOWLEDGE_DIR, lexical_dir=LEXICAL_DIR
    )
    packet_map: dict[str, EvidencePacket] = {
        key: build_packet(sources, key) for key in [str(row["passage_key"]) for row in pilot_rows]
    }
    prediction_map = {
        key: [
            SemanticAssertionCandidate.model_validate(row)
            for row in candidates
            if row["subject_key"] == key
        ]
        for key in packet_map
    }
    exact_map: dict[str, list[str]] = {}
    for key, packet in packet_map.items():
        partners = [
            other for other in packet.exact_parallel_passage_keys if other in prediction_map
        ]
        if partners:
            exact_map[key] = partners
    entity_labels = {}
    for packet in packet_map.values():
        entity_labels.update(
            {mention.entity_key: mention.entity_label for mention in packet.mentions}
        )
    parallel = compare_exact_parallels(prediction_map, exact_map, entity_labels=entity_labels)
    concept_clusters = []
    return {
        "pilot_mantras": len(pilot_rows),
        "processed": len(payloads),
        "no_claims": no_claims,
        "candidate_entities": 0,
        "candidate_assertions": len(candidates),
        "structurally_valid": sum(
            1 for row in validations if row["status"] != "VALIDATION_REJECTED"
        ),
        "validation_rejected": validation_rejected,
        "needs_review": status_counts["NEEDS_REVIEW"],
        "auto_accepted": status_counts["AUTO_ACCEPTED"],
        "assertions_per_mantra": len(candidates) / len(pilot_rows),
        "entities_per_mantra": 0.0,
        "predicate_counts": dict(sorted(predicate_counts.items())),
        "node_type_counts": {"CANONICAL_ENTITY": len(candidates)},
        "explicitness_counts": dict(sorted(explicitness_counts.items())),
        "evidence_linkage_failures": validation_codes.get("EVIDENCE_TOKEN_NOT_IN_PASSAGE", 0)
        + validation_codes.get("EVIDENCE_PASSAGE_NOT_SUPPLIED", 0),
        "fabricated_token_references": validation_codes.get("EVIDENCE_TOKEN_NOT_IN_PASSAGE", 0),
        "unsupported_claims": validation_rejected,
        "metadata_context_conflicts": sum(
            1 for row in validations if row.get("conflicts_with_metadata")
        ),
        "parallel": parallel,
        "batch_stats": batch_stats,
        "concept_clusters": concept_clusters,
    }


def write_reports(stats: dict[str, object]) -> None:
    predicate_lines = (
        "\n".join(f"- `{key}`: {value}" for key, value in stats["predicate_counts"].items())
        or "- none"
    )
    node_lines = "\n".join(
        f"- `{key}`: {value}" for key, value in stats["node_type_counts"].items()
    )
    batch_lines = "\n".join(
        f"- Batch {row['batch']:03d}: {row['mantra_count']} mantras, "
        f"{row['candidate_assertions']} candidates, "
        f"{row['validation_rejected']} rejected, {row['needs_review']} needs review"
        for row in stats["batch_stats"]
    )
    _write(
        REPORT_DIR / "RIGVEDA_SEMANTIC_PILOT_CODEX_LUNA.md",
        f"""# Rigveda semantic pilot — Codex/Luna direct extraction

Run ID: `vedagraph-rigveda-semantic-codex-luna-pilot-1.0.0-rc1`

The 508-mantra pilot was processed from deterministic EvidencePackets in 22 batches.
The extractor runtime was `CODEX_DIRECT`: the Codex/Luna agent authored structured
payloads locally, and Python only parsed, validated, routed, and reported them.

## Results

- Pilot mantras: **{stats["pilot_mantras"]}**
- Successfully processed: **{stats["processed"]}**
- No-claim mantras: **{stats["no_claims"]}**
- Candidate semantic entities: **{stats["candidate_entities"]}**
- Candidate semantic assertions: **{stats["candidate_assertions"]}**
- Structurally valid: **{stats["structurally_valid"]}**
- Validation rejected: **{stats["validation_rejected"]}**
- Needs review: **{stats["needs_review"]}**
- Auto-accepted: **{stats["auto_accepted"]}**
- Assertions per mantra: **{stats["assertions_per_mantra"]:.3f}**
- Entities per mantra: **{stats["entities_per_mantra"]:.3f}**

All valid candidates are review-only because `unlocked_predicates=[]` and the gold
status is `UNANNOTATED`. No precision percentage is claimed.

## Semantic distribution

Predicate distribution:

{predicate_lines}

Node-type distribution:

{node_lines}

Explicitness: `{stats["explicitness_counts"]}`

Evidence-linkage failures: **{stats["evidence_linkage_failures"]}**

Fabricated token references: **{stats["fabricated_token_references"]}**

Unsupported claims detected by deterministic validator: **{stats["unsupported_claims"]}**

Traditional-metadata context conflicts flagged for review: **{stats["metadata_context_conflicts"]}**

## Batch results

{batch_lines}

## Spend and readiness

- API calls: **0**
- Direct API cost: **$0**
- Gold status: **UNANNOTATED**
- Final state: `RIGVEDA_SEMANTIC_PILOT_COMPLETE_AWAITING_HUMAN_GOLD`

This pilot does not authorize semantic extraction over the remaining 10,044 mantras.
""",
    )
    _write(
        REPORT_DIR / "RIGVEDA_SEMANTIC_CANDIDATES.md",
        f"""# Rigveda semantic candidate inventory

This safe aggregate report describes `{stats["candidate_assertions"]}` candidate
assertions from the 508-mantra pilot. The full JSONL remains gitignored because it is
model-authored run output. Every valid assertion routes to `NEEDS_REVIEW`; accepted
assertions: **0**.

## Counts

- Candidate assertions: {stats["candidate_assertions"]}
- Candidate entities: {stats["candidate_entities"]}
- Needs review: {stats["needs_review"]}
- Validation rejected: {stats["validation_rejected"]}
- Explicit: {stats["explicitness_counts"].get("EXPLICIT", 0)}
- Strong inference: {stats["explicitness_counts"].get("STRONG_INFERENCE", 0)}
- Interpretive: {stats["explicitness_counts"].get("INTERPRETIVE", 0)}

The direct extraction policy emitted only a `PRAISES` or `INVOKES` suggestion when the
supplied Griffith line explicitly supported that relation for a canonical entity. It
emitted no claim otherwise, created no new semantic entities, and did not upgrade
deterministic metadata into semantic truth.
""",
    )
    _write(
        REPORT_DIR / "RIGVEDA_SEMANTIC_CONCEPT_REVIEW.md",
        """# Rigveda semantic concept review

The pilot produced **0** `SemanticEntityCandidate` rows. This is intentional: the
Codex-direct pass did not invent concept labels from translation or pretrained
knowledge, and the reviewed semantic registry remains empty. Consequently there are no
duplicate-concept clusters to merge or report from this run.

When future human-reviewed concept candidates exist, exact normalized labels may be
grouped; fuzzy similarity must remain a review queue only. Examples such as `Creation`,
`Cosmic Creation`, and `Cosmogony` must not be auto-merged.
""",
    )
    parallel = stats["parallel"]
    disagreement_lines = (
        "\n".join(
            f"- `{item.left}` vs `{item.right}`: only-left={list(item.only_left)}, "
            f"only-right={list(item.only_right)}"
            for item in parallel.disagreements[:40]
        )
        or "- none"
    )
    _write(
        REPORT_DIR / "RIGVEDA_SEMANTIC_PARALLEL_CONSISTENCY.md",
        f"""# Rigveda semantic exact-parallel consistency

Comparison was limited to exact-parallel partners that both occur in the 508-mantra
pilot. Candidates were compared, never copied across passages.

- Pairs compared: **{parallel.pairs_compared}**
- Identical candidate sets: **{parallel.pairs_identical}**
- Disagreements: **{len(parallel.disagreements)}**

Disagreements are review flags, not automatic repairs:

{disagreement_lines}
""",
    )


def finalize_manifest(stats: dict[str, object]) -> None:
    path = ROOT / "semantic_run_manifest.json"
    manifest = json.loads(path.read_text(encoding="utf-8"))
    manifest["qa_result"] = "PASSED_WITH_WARNINGS"
    manifest["gold_status"] = "UNANNOTATED"
    manifest["unlocked_predicates"] = []
    hashes: dict[str, str] = {}
    for file_path in sorted(ROOT.rglob("*")):
        if not file_path.is_file() or file_path == path:
            continue
        hashes[str(file_path.relative_to(ROOT))] = _sha256(file_path)
    manifest["output_hashes"] = hashes
    path.write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )


def main() -> None:
    build_worksheet()
    stats = build_reports()
    write_reports(stats)
    finalize_manifest(stats)
    print(
        f"reports generated: {stats['candidate_assertions']} assertions, "
        f"{stats['no_claims']} no-claim mantras"
    )


if __name__ == "__main__":
    main()
