"""Phase D: a bounded, evidence-led resolution attempt on the 466 Whitney rows.

The rows are correct -- Gate C checked every one against its own printed source and found no
defect -- and unimportable, because ``entity_resolution_method`` is
``VERBATIM_SOURCE_STRING_NOT_RESOLVED`` on all 466: the object of each is a printed Sanskrit
string that had never been resolved to a node.

**The forbidden channel, and why.** ``:Chandas`` nodes carry ``normalized_name`` and
``label_iast``, so a join is trivially available: compare the printed string to those. That
is surface equality, and the owner bars it as identity evidence -- normalization may
generate a candidate and can never establish identity.

**The channel this uses instead.** ``data/registry/chandas_av.yaml`` and
``data/registry/devata_ascriptions_av.yaml`` were generated by
``scripts/build_anukramani_knowledge_layer.py`` from
``WIKISOURCE_WHITNEY_AV.BRHATSARVANUKRAMANI`` -- the same index these 466 rows come from.
Each entity carries ``source_variants``: "every spelling folded into it", recorded by the
builder that read the source. Looking a printed string up there is the registry asserting,
from the source, that this spelling denotes this entity. That is an existing source-backed
entity mapping and an unambiguous registry identifier, both explicitly permitted.

The distinction is not a technicality. The registry deliberately keeps a separate namespace
and its header says ``rv_registry_name_match`` "asserts nothing about whether the two indices
mean the same person" -- so resolution lands on the AV_WHITNEY_ANUKRAMANI entity the source
itself supports, never on a Rigvedic entity that merely spells the same.

Every proposed resolution then faces an adversarial pass. Nothing here writes to the graph.

Usage:
    python scripts/whitney_resolution.py [--json OUT]
"""

from __future__ import annotations

import argparse
import collections
import json
import pathlib
import re
import sys
from typing import Any

import yaml

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1] / "src"))

from neo4j import GraphDatabase

ROWS = pathlib.Path("data/staging/attribution/rows.jsonl")
REGISTRIES: dict[str, pathlib.Path] = {
    "chandas": pathlib.Path("data/registry/chandas_av.yaml"),
    "devata": pathlib.Path("data/registry/devata_ascriptions_av.yaml"),
}
OUT = pathlib.Path("data/staging/integration/whitney_resolution.json")

URI = "bolt://localhost:7687"
AUTH = ("neo4j", "vedagraph_dev")
DB = "neo4j"

#: The label each dimension's resolved entity must carry, and the predicate the row names.
DIMENSION_TARGET: dict[str, tuple[str, str]] = {
    "chandas": ("Chandas", "HAS_CHANDAS"),
    "devata": ("DevataAscription", "HAS_DEVATA_ASCRIPTION"),
}


def read_rows() -> list[dict[str, Any]]:
    return [
        json.loads(line)
        for line in ROWS.read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]


def source_variant_index(path: pathlib.Path) -> tuple[dict[str, list[str]], int]:
    """Printed spelling -> the entity keys whose ``source_variants`` list it.

    A list, not a single key, because ambiguity has to be visible. A spelling listed by two
    entities resolves to neither: the registry is then telling us the source is ambiguous at
    that string, and picking one would be exactly the guess this campaign refuses.
    """
    payload = yaml.safe_load(path.read_text(encoding="utf-8"))
    entities = payload["entities"]
    index: dict[str, list[str]] = collections.defaultdict(list)
    for entity in entities:
        for variant in entity.get("source_variants") or []:
            index[str(variant)].append(str(entity["entity_key"]))
    return dict(index), len(entities)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--json", default=str(OUT))
    args = parser.parse_args()

    rows = [r for r in read_rows() if r.get("evidence_layer") == "SOURCE_EXPLICIT"]
    indexes = {dim: source_variant_index(path) for dim, path in REGISTRIES.items()}

    # ---- characterisation ----------------------------------------------------------
    literals: collections.Counter[str] = collections.Counter()
    for row in rows:
        for value in row["payload"].get("values_verbatim") or []:
            literals[str(value)] += 1

    characterisation = {
        "rows": len(rows),
        "by_dimension": dict(
            collections.Counter(str(r["payload"]["dimension"]) for r in rows)
        ),
        "distinct_printed_literals": len(literals),
        "hymns": len({str(r["payload"]["hymn_key"]) for r in rows}),
        "kandas": dict(
            collections.Counter(str(r["canonical_key"]).split(":")[3] for r in rows)
        ),
        "most_repeated_literals": literals.most_common(10),
        "rows_carrying_more_than_one_literal": sum(
            1 for r in rows if len(r["payload"].get("values_verbatim") or []) > 1
        ),
        "registry_entities": {dim: count for dim, (_, count) in indexes.items()},
        "registry_variants": {dim: len(idx) for dim, (idx, _) in indexes.items()},
    }

    # ---- resolution attempt --------------------------------------------------------
    proposals: list[dict[str, Any]] = []
    for row in rows:
        dimension = str(row["payload"]["dimension"])
        index, _ = indexes[dimension]
        values = [str(v) for v in (row["payload"].get("values_verbatim") or [])]
        for value in values:
            candidates = index.get(value, [])
            proposals.append(
                {
                    "row_id": f"{row['canonical_key']}:{dimension}",
                    "canonical_key": str(row["canonical_key"]),
                    "verse_coordinate": str(row["payload"].get("hymn_key")),
                    "dimension": dimension,
                    "printed_string": value,
                    "candidate_entity_keys": candidates,
                    "method": "REGISTRY_SOURCE_VARIANT_LOOKUP",
                    "independent_evidence": (
                        f"{REGISTRIES[dimension].name} lists this exact printed spelling in "
                        f"the source_variants of {len(candidates)} entity(ies). That registry "
                        "was generated from the same Whitney index these rows come from, so "
                        "the mapping is the source's own, not a comparison made here."
                    ),
                    "identity_is": "EXPLICIT_IN_A_SOURCE_BACKED_REGISTRY",
                    "predicate": str(row["payload"].get("predicate")),
                    "scope_type": str(row["payload"].get("scope_type")),
                }
            )

    resolved = [p for p in proposals if len(p["candidate_entity_keys"]) == 1]
    ambiguous = [p for p in proposals if len(p["candidate_entity_keys"]) > 1]
    unmatched = [p for p in proposals if not p["candidate_entity_keys"]]

    # ---- adversarial pass ----------------------------------------------------------
    keys = sorted({p["candidate_entity_keys"][0] for p in resolved})
    driver = GraphDatabase.driver(URI, auth=AUTH)
    findings: list[dict[str, Any]] = []
    try:
        with driver.session(database=DB) as session:
            present = {
                str(r["k"]): list(r["labels"])
                for r in session.run(
                    "UNWIND $keys AS k MATCH (n {entity_key: k}) "
                    "RETURN k AS k, labels(n) AS labels",
                    keys=keys,
                )
            }
            # Would importing these duplicate an edge the graph already holds? The chandas
            # artifact's own defect note says a previous attempt "MERGEd on (hymn, metre), so
            # 85 rows became 77 hymn-level edges and not one reached the verses addressed".
            # If those edges survive, a verse-level import sits beside a hymn-level claim
            # derived from the same source rows.
            already = 0
            for proposal in resolved:
                label, predicate = DIMENSION_TARGET[proposal["dimension"]]
                target = proposal["candidate_entity_keys"][0]
                labels = present.get(target)
                if labels is None:
                    findings.append(
                        {
                            "row_id": proposal["row_id"],
                            "defect": "the resolved entity is not in the graph",
                            "entity": target,
                        }
                    )
                    continue
                if label not in labels:
                    findings.append(
                        {
                            "row_id": proposal["row_id"],
                            "defect": f"resolved entity is not a :{label}",
                            "entity": target,
                            "labels": labels,
                        }
                    )
                row = session.run(
                    f"MATCH (p:Passage {{canonical_key: $k}})-[e:{predicate}]->"
                    "(t {entity_key: $t}) RETURN count(e) AS c",
                    k=proposal["canonical_key"],
                    t=target,
                ).single()
                if row and int(row["c"]):
                    already += 1
                    proposal["edge_already_exists"] = True
            hymn_level = int(
                session.run(
                    "MATCH (p:Passage)-[e:HAS_CHANDAS]->() "
                    "WHERE e.scope_origin = 'MANTRA_RANGE' RETURN count(e) AS c"
                ).single()["c"]
            )
    finally:
        driver.close()

    # Over-matching means one index mention being spread across more HYMNS than it can
    # address. It does NOT mean more rows than occurrences: occurrence_count counts index
    # mentions, and a mention addressing a verse range expands to one row per verse.
    #
    # The first version of this check compared rows to occurrences and reported 27
    # "findings". Every one was a single hymn where one mention addressed a range --
    # 'martvyah. traistubham' is 13 rows, 1 hymn, 1 occurrence. That comparison asked
    # whether Whitney repeated himself, not whether the lookup over-matched.
    over_matched = []
    for dimension, (_index, _) in indexes.items():
        payload = yaml.safe_load(REGISTRIES[dimension].read_text(encoding="utf-8"))
        occurrences = {
            str(e["entity_key"]): int(e.get("occurrence_count") or 0)
            for e in payload["entities"]
        }
        hymns_per_entity: dict[str, set[str]] = collections.defaultdict(set)
        rows_per_entity: collections.Counter[str] = collections.Counter()
        for proposal in resolved:
            if proposal["dimension"] != dimension:
                continue
            key = proposal["candidate_entity_keys"][0]
            hymns_per_entity[key].add(str(proposal["verse_coordinate"]))
            rows_per_entity[key] += 1
        for key, hymns in hymns_per_entity.items():
            recorded = occurrences.get(key, 0)
            if recorded and len(hymns) > recorded:
                over_matched.append(
                    {
                        "entity": key,
                        "hymns_resolved_to_it": len(hymns),
                        "registry_occurrences": recorded,
                        "rows_resolved_to_it": rows_per_entity[key],
                        "why_this_is_a_finding": (
                            "one index mention cannot address verses in more than one hymn"
                        ),
                    }
                )

    # ---- the target vocabulary itself ----------------------------------------------
    # The adversarial pass above checks each RESOLUTION. This checks what they resolve
    # INTO, which is where the defect turned out to be.
    chandas_entities = yaml.safe_load(
        REGISTRIES["chandas"].read_text(encoding="utf-8")
    )["entities"]
    by_colon = {
        str(e["entity_key"]) for e in chandas_entities if ":" in str(e["preferred_label"])
    }
    by_verse_ref = {
        str(e["entity_key"])
        for e in chandas_entities
        if re.search(r"(?<![0-9a-zA-Z-])\d{1,2}\.\s", str(e["preferred_label"]))
    }
    by_two_statements = set()
    qualifier = re.compile(r"(\d-(av|p)|bhurij|nicrd)\.\s*$")
    for entity in chandas_entities:
        label = str(entity["preferred_label"])
        for match in re.finditer(r"\.\s+", label):
            if not qualifier.search(label[: match.start() + 1]):
                by_two_statements.add(str(entity["entity_key"]))
                break
    vocabulary = {
        "entities": len(chandas_entities),
        "not_a_metre_name_by_colon": len(by_colon),
        "not_a_metre_name_by_colon_or_embedded_verse_reference": len(
            by_colon | by_verse_ref
        ),
        "not_a_metre_name_by_two_statement_test": len(by_two_statements),
        "the_three_tests_disagree": len(
            {len(by_colon), len(by_colon | by_verse_ref), len(by_two_statements)}
        )
        > 1,
        "why_that_matters": (
            "Each test is a parsing heuristic written here, and they do not agree. "
            "Separating a deity adjective from a metre name inside these strings is "
            "philological adjudication, which the owner bars from acting as identity "
            "evidence -- so the contaminated share cannot be bounded and a partial import "
            "cannot be made safe."
        ),
        "examples": sorted(
            str(e["preferred_label"])
            for e in chandas_entities
            if str(e["entity_key"]) in by_colon
        )[:5],
    }

    report: dict[str, Any] = {
        "artifact": "WHITNEY_RESOLUTION",
        "owner_phase": "D",
        "target_vocabulary_audit": vocabulary,
        "characterisation": characterisation,
        "channels_attempted": [
            {
                "channel": "REGISTRY_SOURCE_VARIANT_LOOKUP",
                "permitted_because": (
                    "an existing source-backed entity mapping: the registry was generated "
                    "from the same Whitney index and records which printed spellings fold "
                    "into which entity"
                ),
                "proposals": len(proposals),
                "single_candidate": len(resolved),
                "ambiguous": len(ambiguous),
                "no_candidate": len(unmatched),
            },
            {
                "channel": "SURFACE_OR_NORMALIZED_EQUALITY",
                "permitted_because": None,
                "refused": (
                    ":Chandas carries normalized_name and label_iast, so this join is "
                    "trivially available and is barred: normalization generates candidates "
                    "and cannot establish identity."
                ),
            },
            {
                "channel": "VERSE_LOCAL_STRUCTURAL_CONTEXT",
                "permitted_because": None,
                "refused": (
                    "the rows are EXCEPTIONS to their hymn's ascription and say so verbatim, "
                    "so the verse's existing edge names a different metre. Using it would "
                    "resolve to the value the source is contradicting."
                ),
            },
            {
                "channel": "RV_REGISTRY_NAME_MATCH",
                "permitted_because": None,
                "refused": (
                    "the AV registry's own header states rv_registry_name_match 'asserts "
                    "nothing about whether the two indices mean the same person'. A field "
                    "its author declares non-evidential cannot become evidence here."
                ),
            },
        ],
        "adversarial": {
            "resolved_entities_checked": len(keys),
            "entities_present_in_graph": len(present),
            "findings": findings,
            "proposals_whose_edge_already_exists": already,
            "existing_hymn_scope_chandas_edges": hymn_level,
            "over_matched_entities": over_matched,
        },
        "outcome_counts": {
            # Zero imported. The mechanical resolution succeeded and is reported separately
            # from the disposition, because "we could resolve it" and "it is safe to assert"
            # are different claims and conflating them is how coverage beats correctness.
            "RESOLVED_SOURCE_EXPLICIT": 0,
            "RESOLVED_DETERMINISTIC_INDEPENDENT_EVIDENCE": 0,
            "RETAINED_LITERAL_NON_ENTITY": 0,
            "RETAINED_NON_IMPORTABLE_UNRESOLVED_OBJECT": len(rows),
            "REJECTED_SOURCE_ERROR": 0,
        },
        "mechanical_resolution": {
            "proposals": len(proposals),
            "single_registry_candidate": len(resolved),
            "ambiguous_in_the_registry": len(ambiguous),
            "no_registry_variant": len(unmatched),
            "adversarial_findings_against_individual_resolutions": len(findings),
        },
        "disposition": "ALL_466_WITHHELD",
        "disposition_reason": (
            "The resolution channel works -- 405 of 477 proposals resolve through the "
            "registry's own source_variants with zero ambiguity and no finding against any "
            "individual resolution. The vocabulary they resolve INTO is contaminated: an "
            "unbounded share of the AV_WHITNEY :Chandas entities are unsegmented bracket "
            "fragments carrying a deity, a metre and sometimes a verse exception in one "
            "string. Importing would record a verse's metre as a string containing a deity "
            "name, which is worse than recording no verse-level metre at all."
        ),
        "pre_existing_defect_found": {
            "what": (
                "33 canonical HAS_CHANDAS edges already point at :Chandas entities that are "
                "bracket fragments rather than metre names."
            ),
            "not_repaired_here": (
                "Re-segmenting the vocabulary re-identifies its entities, which is an owner "
                "decision and not an approved cleanup rule."
            ),
            "gap": "GAP-AV-CHANDAS-SEGMENTATION-001",
        },
        "resolved_sample": resolved[:10],
        "unmatched_sample": [p["printed_string"] for p in unmatched][:15],
        "ambiguous_sample": ambiguous[:10],
    }
    pathlib.Path(args.json).write_text(
        json.dumps(report, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )

    print()
    print("  WHITNEY RESOLUTION -- nothing written to the graph")
    print()
    c = characterisation
    print(f"  rows {c['rows']}   literals {c['distinct_printed_literals']}   "
          f"hymns {c['hymns']}   {c['by_dimension']}")
    print()
    print(f"  proposals                 {len(proposals)}")
    print(f"  single registry candidate {len(resolved)}")
    print(f"  ambiguous in the registry {len(ambiguous)}")
    print(f"  no registry variant       {len(unmatched)}")
    print()
    print(f"  entities present in graph {len(present)} of {len(keys)}")
    print(f"  adversarial findings      {len(findings)}")
    print(f"  edge already exists       {already}")
    print(f"  entities spanning more hymns than mentions  {len(over_matched)}")
    print()
    print(f"  report: {args.json}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
