import { readFile } from "node:fs/promises";
import path from "node:path";

/**
 * The shipped build's provenance, as generated by `scripts/build_frontend_provenance.py`.
 *
 * Read off disk rather than fetched, for the same reason the homepage reads its world slice
 * that way: it is a build artifact that ships in `public/`, so on the server the file is
 * already there and fetching it from our own origin would add a round trip to read a file we
 * are sitting on.
 *
 * Server-only. The types below are hand-written against the generator's output and the
 * contract test in `tests/unit/provenance.test.ts` is what keeps them honest — a shape
 * mismatch fails there rather than rendering an empty section.
 */

export type ProvenanceArtifact = {
    artifact_id: string;
    title: string | null;
    edition_title: string | null;
    source_edition: string | null;
    editors: string[] | null;
    electronic_editors: string[] | null;
    contributors: string[] | null;
    publication_date: string | null;
    retrieval_date: string | null;
    format: string | null;
    language: string | null;
    recension: string | null;
    rights_status: string | null;
    license_url: string | null;
    url: string | null;
    work_id: string | null;
};

export type ProvenanceEntry = {
    layer: string;
    source_id: string;
    name: string;
    organization: string | null;
    url: string | null;
    authority_tier: string | null;
    /** What these files are held under. May differ from the site's own statement. */
    rights_status: string[];
    /** What the source site states, which is not always what the file states. */
    site_rights_status: string | null;
    rights_url: string | null;
    vedas: string[];
    contributes: string;
    evidence: string;
    artifacts: ProvenanceArtifact[];
};

export type ProvenanceWork = {
    work_id: string;
    veda: string;
    work_name: string;
    abbreviation: string;
    recension: string;
    hierarchy: string[];
    scope: string;
    completeness: string;
    excluded_corpora: string[];
    canonical_build: string;
};

export type Provenance = {
    generator: string;
    inputs: string[];
    layers: { id: string; label: string; note: string }[];
    works: ProvenanceWork[];
    entries: ProvenanceEntry[];
    totals: {
        sources: number;
        artifacts: number;
        registered_sources: number;
        registered_artifacts: number;
    };
};

let cached: Provenance | null = null;

export async function readProvenance(): Promise<Provenance> {
    if (cached) return cached;
    const file = path.join(process.cwd(), "public", "data", "provenance.json");
    cached = JSON.parse(await readFile(file, "utf8")) as Provenance;
    return cached;
}

/** The registry's own division names for one collection, e.g. Mandala → Sukta → Mantra. */
export function hierarchyOf(provenance: Provenance, veda: string) {
    return provenance.works.find((work) => work.veda === veda)?.hierarchy ?? null;
}
